### PR TITLE
Detect fullscreen denies and manual fullscreen changes

### PR DESCRIPTION
**Pull request by twiss**
Only tested in Chrome.

### CODE REVIEW

**Comment by ferndot** [comment]
This is a perfect implementation. However, there is a bug on Firefox OS that causes it to exit fullscreen (and switch UIs) every time the user clicks on the editor to make an input. It is quite a nasty experience, and I am filing a bug.

Do you think that we should still land this, or wait?

**Comment by twiss** [comment]
Oh, right, you mentioned that. Yeah, don't merge if this makes it worse.

**Comment by ferndot** [comment]
The bug is here: [1105886](http://bugzil.la/1105886)

**Comment by twiss** [comment]
Chrome Android actually has the same behavior. I'll investigate for a fix.

Edit: it doesn't actually go out of fullscreen mode, though, in the sense that if you close the keyboard, you go back into fullscreen. The changes in this PR don't change anything.

Edit 2: Have you tested this patch on Firefox OS? I don't think there's a way around it, it even happens with a minimal testcase with a textarea.

**Comment by ferndot** [comment]
In Android, does the UI switch when the keyboard appears? If not, then that is fine.

I have tested on Firefox OS, and that is where the issue occurs. There is no way around it, unless we use a function that only changes the UI manually (not by listening for the `fullscreenchange` event).

Maybe, we should just land it, and I will escalate the bug for the Mozilla folks?

**Comment by twiss** [comment]
> In Android, does the UI switch when the keyboard appears? If not, then that is fine.

No, even with this patch the UI remains in fullscreen mode when opening the keyboard.

**Comment by ferndot** [comment]
Merged! Thank you @twiss!

**Pull request merged**
