### PR TITLE
Add a max-height to the desktop menu

### PR DESCRIPTION
**Pull request by twiss**
From #207:

> Also, I tried to give it a max-height and keep the scrollbar intact, but couldn't get it to work

Figured it out.

firetext-menu-max-height

### CODE REVIEW

**Comment by ferndot** [comment]
Looks nice in regular modes. RTL language support is broken, though...

**Comment by ferndot** [comment]
Also, night mode has several issues, including an artifact.

screen shot 2014-11-28 at 9 34 13 pm

**Comment by twiss** [comment]
Thanks for paying attention! Both fixed.

**Comment by ferndot** [comment]
Fixes confirmed, I am merging! You are on a roll, @twiss =)

**Comment by twiss** [comment]
Haha, thanks, I should be working in night mode myself by now.

**Pull request merged**
