### PR TITLE
Add margin indicators

### PR DESCRIPTION
**Pull request by twiss**
In #201 and #205 I've been talking about some sort of border, but I thought this looked better.

### CODE REVIEW

**Comment by ferndot** [comment]
I like the minimalism of these indicators :+1:!

The indicators remain at the bottom of the screen in documents that are smaller than the editor (because of the edit DIV's fixed height). Is this trivial enough to overlook?

**Comment by twiss** [comment]
That would indeed be better, not super easy though. I'll try fixing it later.

**Comment by twiss** [comment]
Here you go. This commit probably deserves testing on a multitude of browsers and documents, including new and empty ones, if you can.

**Comment by ferndot** [comment]
The patch functions well on:
- Firefox Desktop
- Firefox OS

**Comment by twiss** [comment]
Alright, great. Do you want me to merge?

**Comment by ferndot** [comment]
Sure!

**Pull request merged**
