### PR TITLE
Fix #194

### LINKED ISSUE #194: Merge module system changes into develop
I was dumb, and pushed changes to the module system into the filesystem-2 branch. This action prevents the new module system from being used until that feature lands.

TODO: Separate all module-specific changes from the filesystem-2 branch, and merge them into the develop branch.

### PR DESCRIPTION
**Pull request by ferndot**
This pull request will fix issue #194! Any thoughts before I merge it?

### CODE REVIEW

**Comment by twiss** [comment]
> Any thoughts before I merge it?

Nothing from me.

**Comment by ferndot** [comment]
@twiss: great! I fixed one more issue. Now, I will merge =)

**Comment by twiss** [comment]
Actually, this seems to have broken document creation in Chrome desktop. Sorry I didn't notice earlier, do you want me to PR a revert?

**Comment by ferndot** [comment]
@twiss do you get the "You have not setup a storage method" notice?

**Comment by twiss** [comment]
Yeah

**Comment by ferndot** [comment]
Let me check. I get that message too.

**Comment by ferndot** [comment]
I fixed the issue in b00c63a125cbb813e4f8eac51167c7ea2fdffdc1!

**Comment by twiss** [comment]
Confirmed fixed, thanks.

**Pull request merged**
