### PR TITLE
Reorganize top bar buttons

### PR DESCRIPTION
**Pull request by twiss**

### CODE REVIEW

**Comment by ferndot** [comment]
Thank you @twiss!

I am experiencing an issue that prevent me from pulling from Github right now =( I will review this as soon as I can get it fixed.

From an inspection of the code, it looks good. I just need to test it.

**Comment by ferndot** [comment]
I have a few minor nitpicks/questions:
- Why did you move the settings button to the right of the sidebar?
- Firetext wordmark is not centered on welcome view
- Menu button does not show in Zen mode with autosave off.

Other than that, it looks good. Major kudos to you for remembering to edit the rtl css!

**Comment by twiss** [comment]
Thanks for reviewing.
- I thought it looked better. I've backed out that commit.
- Hmm. If I center it perfectly though, it doesn't look that good either. Should I put it on the left? (See screenshots.)
- Should be fixed now.

firetext-centered-left

**Comment by ferndot** [comment]
Thanks for the updates!

Hmm, this is tricky (the opposing buttons gave visual balance). It is probably best to put the wordmark on the left. Can you make sure that it is aligned with the list headers below it? I believe that they have `padding-left: 1.5rem`. Also, you can remove the desktop override in https://github.com/codexa/firetext/blob/develop/style/desktop.css#L85-L92.

**Comment by twiss** [comment]
Alright. What is `style/bb/`? Should I change it there?

**Comment by ferndot** [comment]
`style/bb` is for Firefox OS building blocks.

Can you add the style into https://github.com/codexa/firetext/blob/develop/style/main.css? The wordmark uses a `.firetext` css class. It inherits other styles from https://github.com/codexa/firetext/blob/develop/style/bb/headers.css.

**Comment by twiss** [comment]
Thanks, done.

**Comment by ferndot** [comment]
Just one more thing: can you align the wordmark to the right in rtl mode? As soon as that is done, I will merge this pull request!!!

**Comment by twiss** [comment]
Of course. Done.

**Comment by ferndot** [comment]
Fantastic :+1: 

I will merge presently.

**Comment by ferndot** [comment]
@jackd1: can you merge this please? I am having terrible computer issues =(

**Comment by jackd1** [comment]
I'll try. I may be able to by today or otherwise not until Sunday.

**Comment by twiss** [comment]
@jackd1, @joshua-s gave me push access, so I'll merge it.

**Pull request merged**
