### PR TITLE
Fix scrolling in night mode

### PR DESCRIPTION
**Pull request by twiss**

### CODE REVIEW

**Comment by ferndot** [comment]
Can you synchronize this PR?

**Comment by twiss** [comment]
Done.

**Comment by ferndot** [comment]
Sorry @twiss this runs very slowly on my flame. Also, the original method now scrolls in FFOS.

**Comment by twiss** [comment]
Do you know if the broken scrolling exists on release versions of FFOS in the wild?

**Comment by ferndot** [comment]
1.2+ at least have no problems. I can't test 1.1 atm because of the other errors.

**Pull request closed without merging**
