### PR TITLE
Editor proxy

### PR DESCRIPTION
**Pull request by jackd1**
This fixes problems catching events on the editor and uses a polyfill to support messageChannel in firefox.

### CODE REVIEW

**Comment by jackd1** [comment]
I can merge this if you guys are all okay with this.

**Comment by ferndot** [comment]
Let me test a bit first.  Good work :)

**Comment by jackd1** [comment]
Ok, make sure to change http://localhost:81 on line 47 of editorProxy.js to whatever host you're serving it from, for Firefox OS, it's app://[app-id]

**Comment by ferndot** [comment]
:crying_cat_face: 

I changed line 47 to `if(e.origin !== window.location.host) {`, and on http://firetext.codexa.org/beta it works like a charm.  Unfortunately, it breaks on my device.  It seems that the app:// protocol is treated like a local protocol :(

Is there any way to bypass this issue that you know of?

**Comment by jackd1** [comment]
It should be using window.location.origin which will give the full protocol, host, and port.  However, Firefox gives null for this paramater for blob URLs anyway, which I believe is not the correct behavior, but I'll have to check the spec.  We can either directly hard code the origin in editorProxy.js, or have the ajax loader insert it automatically.

**Comment by jackd1** [comment]
I added a mainOrigin variable which gets filled with the main document's origin.

**Comment by ferndot** [comment]
It works now!  Let me merge this so it doesn't remove the changes in master.

**Comment by jackd1** [comment]
Great :+1:

**Comment by ferndot** [comment]
Great job @jackd1!

**Comment by jackd1** [comment]
Thanks! :smile:

**Pull request merged**
