### PR TITLE
Html preview sanitize

### PR DESCRIPTION
**Pull request by asdf23**
Adds a cleanup for preview. We should do some more testing on it, but I think it works for any file created by the editor.

### CODE REVIEW

**Comment by ferndot** [comment]
Awesome!

**Comment by ferndot** [comment]
Awesome!  Let me test this :)

**Comment by ferndot** [comment]
Looks like it works :)  Don't be offended though if I revert this because a test fails (we are shipping today).  I will get it in the next release if that happens ;)

**Comment by ferndot** [comment]
It works well, but there is one issue with 2nd level files on FFOS 1.1.  I will troubleshoot, could you as well?  Other than that, you nailed it!

**Comment by ferndot** [comment]
@Codexa, @asdf23:
I get this error: 22:27:41.883 SyntaxError: invalid quantifier firetext.js:343

**Comment by asdf23** [comment]
@Codexa I'm not sure why you are getting that. That area of code is removing br tags. Could you (somehow) attach the file that is causing the error?

@Joshua-S  you said "there is one issue with 2nd level files on FFOS 1.1" Sorry I'm not quite following what you mean by that.

**Comment by ferndot** [comment]
@asdf23 it is all the same bug.

I will mail the file to you.  Put it in a folder like this Documents/prospector.html.

**Comment by ferndot** [comment]
All:
It is on Dropbox at https://www.dropbox.com/s/7kltshk4bimk2ty/prospector.html
The issue is in these lines: https://github.com/Codexa/Firetext/blob/v0.3/scripts/firetext.js#L342-L343

**Pull request merged**
