### PR TITLE
Issue215 - Show spinner while updating docs on device list

### PR DESCRIPTION
**Pull request by staritza**

### CODE REVIEW

**Comment by ferndot** [comment]
@staritza thank you for taking this!

Since the `updateDocLists()` function relies upon callbacks, placing a `spinner()` at the beginning and end will not show the spinner for the full duration of the document update. Maybe, you could move the `spinner()` to line 316, and the `spinner('hide')` to line 319 in `firetext.js` (before and inside the `firetext.io.enumerate()` function)?

Also, to ensure that the spinner is shown for cloud integrations, you could put `spinner()` on [line 97](https://github.com/codexa/firetext/blob/develop/scripts/cloud/cloud.js#L97), and `spinner('hide')` on [line 99](https://github.com/codexa/firetext/blob/develop/scripts/cloud/cloud.js#L99) of [cloud.js](https://github.com/codexa/firetext/blob/develop/scripts/cloud/cloud.js).

**Comment by staritza** [comment]
Ohh thought calling spinner the way i did would eliminate the need to call it in cloud.js. Sorry..new to js. Will fix this in a bit. Thanks!

**Comment by ferndot** [comment]
No problem @staritza!

By the way, you can add a new commit to your branch to update the pull request. That way, you won't need to delete the pull and open a new one =)

**Comment by staritza** [comment]
Oops already did the exact opposite. Was thinking that if the commit was wrong, there was no need merging that with the main branch. Thanks though!

**Pull request closed without merging**
