### PR TITLE
EO translation + IT typos fixed

### PR DESCRIPTION
**Pull request by airon90**
I fixed some errors in Italian translations and I created the Esperanto translation.
I hope that Esperanto letters are correctly rendered: are Ĉĉ Ĝĝ Ĥĥ Ĵĵ Ŝŝ Ŭŭ special characters or are they correctly handled?

### CODE REVIEW

**Comment by jackd1** [comment]
It will depend on the encoding used to serve the page as to whether the characters are correctly handled.  I believe we are using UTF-8 which should work fine.

**Comment by ferndot** [comment]
@Airon90 thank you for this!  Two more things that should be done before we merge:
1) Add Esperanto in Esperanto to the list in https://github.com/codexa/firetext/blob/develop/index.html#L626-L639.  (Characters need to be html encoded).
2) Do `git rebase -i` and use squash to combine your commits into a single commit.  If you are not able to do this, it is fine =)

Thank you again for the awesome work!

One small note: we have a translation project on [Transifex](https://www.transifex.com/projects/p/firetext/) for easy translation creation and editing.  You might want to check it out!

**Comment by airon90** [comment]
@joshua-s 
1. Done
2. I never used git (I installed to use it with AUR packages on Arch Linux). What should I have to do? Please teach me or link me something! 
3. Wow, I did that hard work on GitHub when I could have done by using Transifex. Can I edit readme.md to add that information? Does Transifex automatically add EO translation or do I have to do it by hand?

Thankl you for your work! I'm waiting for my new Flame device to use your app on Firefox OS *-*

**Comment by jackd1** [comment]
If you have never used git, don't worry, one of us should be able to sqwash your commits.  Also, that's probably a good idea, I'll make the readme edit.

**Comment by ferndot** [comment]
You can follow http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html, but as @jackd1 said, we would be fine with doing it for you.

The steps you would take are:
1) cd to your local Firetext repository.
2) Run `git checkout develop` to switch to your develop branch.
3) Run `git rebase -i fdac6c0cbe5f39135dd93151dc910e1441d375cc`.  This means "do an interactive rebase against commit id fdac6c0cbe5f39135dd93151dc910e1441d375cc.
4) Your command line editor would open up a screen like this: 
screen shot 2014-07-09 at 10 01 07 am

5) Change all "pick" to "squash" except the first one.
6) Save and exit the editor.  (For VIM on OS X, it is Shift-:-X).
7) Rebase completes, and then you do `git push --force` to send your changes to github.

Also, please do edit README.MD (maybe in another Pull Request).  I apologize for the lack of information; we have been planning to make a more informative one, but haven't done it yet.  I have requested to add an EO translation on Transifex (@jackd1 please confirm it).

Enjoy the app on your flame =)  You can download it from https://marketplace.firefox.com/app/firetext.  The version on the Marketplace does not have the EO locale yet, but I am planning to ship at least a few new locales soon.

**Comment by airon90** [comment]
@joshua-s Done. I got mad with vi :anger: 

Thank you for the information, I'd like to learn so that someday I could code by my own without bothering people :)

When we close this commit I will open the second one with edit on readme.md ;)

**Comment by ferndot** [comment]
Great, thank you!

This thing looks ready for merge, :+1:!

**Comment by ferndot** [comment]
@Airon90 FYI, EO translation is now located here: https://www.transifex.com/projects/p/firetext/language/eo/

=)

**Comment by airon90** [comment]
Thank you, I'm working on Marketplace translation :)

**Pull request merged**
