### PR TITLE
Update sidebar style (Fix #207)

### LINKED ISSUE #207: [desktop] Chrome-style menu
Maybe it makes more sense to make the menu some sort of dropdown instead of a sidebar on the desktop?

### PR DESCRIPTION
**Pull request by ferndot**
Refines the sidebar introduced by #207.

### CODE REVIEW

**Comment by twiss** [comment]
You could make `::after` an identical but slightly smaller triangle in the same spot, with a white border.

**Comment by twiss** [comment]
Also, there's a scrollbar there:
firetext-scrollbar

**Comment by ferndot** [comment]
I have addressed those comments!

screen shot 2014-11-28 at 2 42 30 pm

**Comment by twiss** [comment]
:+1:

My last nitpick would be the arrow in combination with the border-radius. Possible improvements:
`border-bottom-left-radius: 0`
or
`border-top-right-radius: 6px 15px;` and move the arrow 4px to the left and the menu 4px to the right
or 
`border-radius: ~8px;` and move the arrow ~10px to the left and the menu ~.8rem to the right

See which (if any) of those you like better.

**Comment by ferndot** [comment]
@twiss I took your third suggestion!

**Comment by twiss** [comment]
Looks great! :)

**Pull request merged**
