### PR TITLE
Update to dropbox.js 0.10.3

### PR DESCRIPTION
**Pull request by twiss**
WIP. This fixes the OAuth flow on the desktop.

Dropbox complains with `Invalid client_id: "CBB0GYTWGYA=|aeSB7VBcIP94mzfQPoykIzGm++Z97KtaDn2snjXCGQ==".`, though. I'm guessing wherever you got your current one you could get a new (OAuth2) one?

However, are you actually supposed to put your key in the source here?

### CODE REVIEW

**Comment by ferndot** [comment]
I think that it is okay to expose the key in the source (https://github.com/dropbox/dropbox-js/blob/stable/guides/getting_started.md#initialization). My only concern is that people could use it for their own apps. I don't know how to mitigate this without making it impossible for others to develop the cloud integrations.

**Comment by ferndot** [comment]
Maybe, I could store the key on the server, and the app could retrieve it when it polls the server for URLs? Since this is JS, the key will be exposed either way.

**Comment by twiss** [comment]
Yeah, that doesn't really matter. So long as other developers can't read users' documents it's ok.

**Comment by ferndot** [comment]
@twiss I have discovered an issue. We do not have access to a domain with an SSL certificate. OAuth2 does not allow non-https domains, except for localhost.

**Comment by twiss** [comment]
Well, that's inconvenient, but Firetext works fine in Firefox on localhost. So it means you can't test Dropbox (completely) in Chrome, and that you have to test Firefox on localhost.

**Comment by ferndot** [comment]
Yeah. Localhost is fine for desktop browsers, but Firefox OS and possibly Firefox for Android use the app:// protocol. And, the apps have no set domain.

**Pull request closed without merging**
